version: '3.3'
services:

#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
#    volumes:
#      - ../frontend/:/app/result_build/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: yandex-foodgram
    container_name: yandex-foodgram
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
